### PR TITLE
Customer, Supplier, Item model initial commit

### PR DESCRIPTION
**Pull request by shivam1708**
1. Supplier model (Party model) added.
2. New Suppliers/Customers gets added to database.
3. On Suppliers page, displays Customers and Suppliers separately and an option to add new Supplier/Customer.

### CODE REVIEW

**Comment by shivam1708** [comment]
@rmehta @Zlash65 please review

**Comment by Zlash65** [comment]
Hi Shivam, can you update your pr with the discussion we had and also initiate the hamburger view implementation.

**Comment by shivam1708** [comment]
1. Hamburger menu has options for Home, Customers, Suppliers, Items.
2. For Customers, Suppliers, Items:
    a. Insert new entry added (connected to Frappe.js)
    b. Update a particular entry (connected to Frappe.js)
    c. List all entries.
3. Navigation done between pages.
4. Inside pages folder seperate folders created for insert,update pages so as to maintain seperation.
5. Generic List to display list of doctypes (currently customers,suppliers,items).
6. Simple UI 
7. Basic validation done for input fields although more to be done

**Comment by shivam1708** [comment]
@rmehta @Zlash65  please review!

**Pull request merged**
